### ISSUE TITLE
Feature Request: Admin /addmoney feature restored

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [BreezyTheDev/ND_Pay#1]
Would it be possible to have another update to this to restore the feature for /addmoney like we used to have with the standalone currency system? Permissions based on ace perms like before or steam hex perhaps.

Its simply not feasible to do it via database at all.

Thank you!

**Comment by breezythdev** [comment]
So you can give yourself or others money correct?

**Comment by Legacy-TacticalGamingInteractive** [comment]
For us admins and server owners to be able to give others money without paying them from our personal account. For such uses as in game cash events, prizes, loans for their RP businesses etc.

**Comment by breezythdev** [comment]
I just pushed out the update. Thanks for the idea.

**Comment by Legacy-TacticalGamingInteractive** [comment]
Thank you!
